CREATE TABLE driver_performance_evaluations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    driver_id INT NOT NULL,
    driver_name VARCHAR(100) NOT NULL,
    date DATE NOT NULL,
    vehicle_type VARCHAR(100),
    vehicle_plate_no VARCHAR(50),
    destination VARCHAR(100),
    purpose_of_travel VARCHAR(100),
    duration_of_travel VARCHAR(50),
    r1 TINYINT,
    r2 TINYINT,
    r3 TINYINT,
    r4 TINYINT,
    r5 TINYINT,
    r6 TINYINT,
    r7 TINYINT,
    r8 TINYINT,
    remarks1 TEXT,
    remarks2 TEXT,
    remarks3 TEXT,
    remarks4 TEXT,
    remarks5 TEXT,
    remarks6 TEXT,
    remarks7 TEXT,
    remarks8 TEXT,
    comments TEXT,
    evaluated_by VARCHAR(100),
    noted_by VARCHAR(100),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (driver_id) REFERENCES users(id) ON DELETE CASCADE
);
